# Generated by Django 4.0.10 on 2024-06-06 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_resegna_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portadas/'),
            preserve_default=False,
        ),
    ]
