# Generated by Django 4.0.10 on 2024-06-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_libro_portada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'permissions': [('special_status', 'Puede leer todos los libros')]},
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portadas/'),
        ),
    ]
