# Generated by Django 4.0.10 on 2024-06-07 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_alter_libro_options_alter_libro_portada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resegna',
            old_name='resenha',
            new_name='resegna',
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='libros.libro')),
            ],
        ),
    ]
