# Generated by Django 4.0.10 on 2024-06-08 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('relacionadas', models.ManyToManyField(blank=True, related_name='relacionadas_con', to='licores.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Licor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes/')),
                ('descripcion', models.CharField(max_length=200)),
                ('categorias', models.ManyToManyField(related_name='libros', to='licores.categoria')),
            ],
            options={
                'permissions': [('special_status', 'Puede leer todos los libros')],
            },
        ),
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resenha', models.CharField(max_length=255)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('licor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenhas', to='licores.licor')),
            ],
        ),
    ]
