# Generated by Django 4.0.10 on 2024-06-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licores', '0004_wishlist_itemwishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='licor',
            name='cantidad',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
