# Generated by Django 4.0.10 on 2024-06-11 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import licores.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licores', '0006_licor_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licor',
            name='creador',
            field=models.ForeignKey(blank=True, default=licores.models.Licor.get_default_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
